; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = v2

[env]
framework = arduino
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.filesystem_size = 0.5m
board = rpipico
lib_deps = 
	FastLED/FastLED@^3.10.3

[env:v1]
build_flags = 
	-std=c++20 -DKISSFFT_DATATYPE=int16_t -DFIXED_POINT=1 -DHARDWARE_VERSION=1
lib_deps = fastled/FastLED@^3.10.3

[env:v2] # MakerFaire 2025 hardware
build_flags = 
	-std=c++20 -DKISSFFT_DATATYPE=int16_t -DFIXED_POINT=1 -DHARDWARE_VERSION=2
