; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board_build.filesystem_size = 0.5m
board = rpipico
lib_deps = 
	FastLED
	kissfft ; https://github.com/mborgerding/kissfft.git
	; https://github.com/earlephilhower/arduino-pico
build_flags =
	-std=c++20 -D PIN_PDM_DIN=18 -D PIN_PDM_CLK=16
lib_extra_dirs = arduino-pico/libraries/I2S
