# PlatformIO pre-build script: stamp each build with the current unix time so
# boards can tell which of them runs the newest firmware (see src/buildid.h and
# src/fwpush.h). Only main.cpp's translation unit includes the stamp, so only
# that file recompiles per build.
import os, time
Import("env")
path = os.path.join(env.subst("$PROJECT_DIR"), "src", "build_epoch.h")
with open(path, "w") as f:
    f.write("// generated by scripts/build_epoch.py at build time -- do not edit or commit\n")
    f.write("#pragma once\n#define BUILD_EPOCH_UNIX %du\n" % int(time.time()))
