// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //
// from https://github.com/forshee9283/pio-touch
// manually generated due to https://github.com/platformio/platform-raspberrypi/issues/10

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// touch //
// ----- //

#define touch_wrap_target 12
#define touch_wrap 19
#define touch_pio_version 0

static const uint16_t touch_program_instructions[] = {
    0x8080, //  0: pull   noblock                    
    0xa041, //  1: mov    y, x                       
    0x6061, //  2: out    null, 1                    
    0x407b, //  3: in     null, 27                   
    0xe09f, //  4: set    pindirs, 31                
    0xe01f, //  5: set    pins, 31                   
    0xe280, //  6: set    pindirs, 0             [2] 
    0x4605, //  7: in     pins, 5                [6] 
    0xa026, //  8: mov    x, isr                     
    0x00a0, //  9: jmp    x != y, 0                  
    0x00e2, // 10: jmp    !osre, 2                   
    0x8020, // 11: push   block                      
            //     .wrap_target
    0xa041, // 12: mov    y, x                       
    0x407b, // 13: in     null, 27                   
    0xe09f, // 14: set    pindirs, 31                
    0xe01f, // 15: set    pins, 31                   
    0xe280, // 16: set    pindirs, 0             [2] 
    0x4605, // 17: in     pins, 5                [6] 
    0xa026, // 18: mov    x, isr                     
    0x00a0, // 19: jmp    x != y, 0                  
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program touch_program = {
    .instructions = touch_program_instructions,
    .length = 20,
    .origin = -1,
    .pio_version = touch_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config touch_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + touch_wrap_target, offset + touch_wrap);
    return c;
}

// this is a raw helper function for use by the user which sets up the GPIO output, and configures the SM to output on a particular pin
void touch_init(PIO pio,uint sm,uint offset, uint pin, uint pin_count, float pio_clk_div){
int i;
for(i=0; i< pin_count; i++) {
    pio_gpio_init(pio, pin + i);
    gpio_pull_down(pin + i);
    //gpio_set_drive_stregnth(pin = i, 4);
    //gpio_set_slew_rate(pin + i);//what rate do we need and what settings can this be?
    }
pio_sm_config c = touch_program_get_default_config(offset);
sm_config_set_clkdiv(&c, pio_clk_div); //Tune speed for sensitivity
sm_config_set_set_pins(&c, pin, pin_count);
sm_config_set_in_pins(&c, pin);
sm_config_set_in_shift(&c, false, false, 32);
pio_sm_init(pio, sm, offset, &c);
}

#endif

